steps:
- task: Docker@2
  displayName: Login to docker-hub
  inputs:
    command: login
    containerRegistry: dockerhub
- task: Docker@2
  displayName: Build AND Push
  inputs:
   command: buildAndPush
   repository: pippo1988/test
   tags: |
     test
- task: KubernetesManifest@0
  displayName: deploy app to dev cluster
  inputs:
   kubernetesServiceConnection: dev
   manifest: test/deployment.yml
   

