apiVersion : apps/v1
kind: Deployment
metadata:
  name: test 
spec:
  replicas: 1
  selector:
    app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test 
          image: orion.azurecr.cn/test
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
  name: test
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: test
